// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("build")>]
[<assembly: AssemblyProductAttribute("LambdaCalc")>]
[<assembly: AssemblyDescriptionAttribute("Stripped-down lambda calculus")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "build"
    let [<Literal>] AssemblyProduct = "LambdaCalc"
    let [<Literal>] AssemblyDescription = "Stripped-down lambda calculus"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
